### ISSUE TITLE
Virgo's dmesg

### ISSUE THREAD

**Issue by DrRamm** [xiaomi-classic-dev/android_device_xiaomi_virgo#1]
Can I ask u about some help? We need a full virgo's dmesg from start (for 3.10 kernel development). Pls, upload it on gist

**Comment by GuaiYiHu** [comment]
https://gist.github.com/GuaiYiHu/8ca44e0dc62f3dcb58aa4b09181128af

**Comment by DrRamm** [comment]
Thanks a lot
