### ISSUE TITLE
Commonize 

### ISSUE THREAD

**Issue by DrRamm** [xiaomi-classic-dev/android_device_xiaomi_virgo#2]
I've started commonize tree (https://github.com/DrRamm/android_device_xiaomi_msm8974/tree/common) but faced with few difficults:
1. https://github.com/xiaomi-note-dev/android_device_xiaomi_virgo/commit/f87775e236e990172bfa30601ada95a25b29052d - Cant figure out is it compatible with cancro
2. https://github.com/xiaomi-note-dev/android_device_xiaomi_virgo/commit/9da863e7ae392d28a2bd495ae655fca72f7b16e0 - rootdir/root/init.class_main.sh - where u took this stuff? 
3. https://github.com/xiaomi-note-dev/android_device_xiaomi_virgo/commit/0dc2956aa890b66c8c5e3e1e20bc043880b14763 - which properties are common or virgo only

**Comment by GuaiYiHu** [comment]
They all took from Ivan's aosp.

**Comment by DrRamm** [comment]
Okay, will wait for oreo branch, i m almost have prepared tree (at least i think so)

**Comment by GuaiYiHu** [comment]
In kernel source, xiaomi uses get_hw_version to differ this three devices.
Mi 3 3
Mi 4 4
Mi note LTE 5
We can add a node in kernel, and make libinit to change the prop. In fact , I don't want to use a common repo, I want to make all these devices be built with a same repo just like miui. Xiaomi put all the mi 3 and mi 4 things in mi note's miui, so mi 3 and mi 4 can flash virgo's rom. 
I am a student and I am having exams these days. I shall try to do this in the winter holiday which comes two weeks later.
I have Mi 3 and Mi note, but I don't have a Mi 4.

**Comment by GuaiYiHu** [comment]
@DrRamm BTW, do you and the other guy use telegram or slack? 
We shall discuss in tg or slack rather than in an issue, that will be more comfortable.

**Comment by DrRamm** [comment]
@GuaiYiHu  sure, @drramm pm me in tg

**Comment by GuaiYiHu** [comment]
OK, got it. 
I'm studying in the library. So… see you a few hours later~~~XD

**Comment by DrRamm** [comment]
Is that u @FlymeDev_GuaiYiHu ?

**Comment by GuaiYiHu** [comment]
Yup

**Comment by DrRamm** [comment]
nice, i.ve pm
