### ISSUE TITLE
HDR and Video recording doesn't work.

### ISSUE THREAD

**Issue by GuaiYiHu** [xiaomi-classic-dev/android_device_xiaomi_virgo#4]
F libc    : Fatal signal 8 (SIGFPE), code -6, fault addr 0x18b in tid 3434 (CAM_JpegProc), pid 395 (cameraserver)

**Comment by ShivamKumarJha** [comment]
Same issue & log in cancro

**Comment by GuaiYiHu** [comment]
Fixed with oss camera hal
